In [9]:
import numpy as np
import pandas as pd
import os
import nltk
import gensim
path = os.getcwd()
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [37]:
clf_deleted = pd.read_csv(path + '\\dbow_deleted_clean.csv')
clf_deleted.drop('Unnamed: 0',axis=1,inplace=True)
tfidf = pd.read_csv(path + '\\tfidf.csv')
tfidf.drop('Unnamed: 0',axis=1,inplace=True)
clf_not_deleted = pd.read_csv(path + '\\dbow_not_deleted_clean.csv')
clf_not_deleted.drop('Unnamed: 0',axis=1,inplace=True)

In [38]:
clf_deleted.head()

,3,0,1,2,3.1,4,5,6,7,8,...,40,41,42,43,44,45,46,47,48,49
0,7,0.424110,-0.028161,1.494008,-0.322786,-0.635714,-0.026492,-0.202188,0.110722,-0.404344,...,0.160453,-0.209065,0.538139,0.096737,0.077176,-0.521673,-0.713271,0.914198,0.737814,-1.176615
1,7,0.045698,-0.935160,0.276119,0.636900,-0.093229,0.265166,-0.190593,0.353573,-0.097209,...,1.213075,-1.561762,1.435802,-0.813427,-0.338660,0.479474,-0.835169,-0.318226,0.471142,-1.056961
2,7,0.968047,0.480199,1.093752,1.259547,-0.475314,1.399264,-0.131330,0.234429,0.362993,...,-0.031708,0.162265,0.918858,-0.166147,0.706717,0.628321,0.536072,1.234146,0.209239,-0.528847
3,7,1.971360,0.289312,0.706755,0.664045,-0.546268,-0.487163,-2.122506,0.126287,-1.133670,...,-0.231073,0.592925,-0.527981,-0.538932,0.199657,-0.172457,-1.069350,1.113648,0.278832,-0.849196
4,7,-0.187793,-0.220327,0.075869,-0.820222,0.792798,-0.201013,-1.242826,0.637620,-0.672921,...,0.286201,-1.211518,0.258506,-0.231914,-0.259462,-0.673891,-0.096882,0.426336,0.582628,-0.773283

In [39]:
tfidf.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,3.1
0,0.000738,0.058065,-0.004589,-0.005728,-0.027311,0.006399,0.001338,-0.023268,0.035641,0.009305,...,-0.022002,-0.040076,0.012896,-0.023432,-0.006918,0.018920,0.027596,0.011532,-0.003910,7
1,0.000574,0.044476,-0.006165,-0.001148,-0.020813,0.012142,0.001605,-0.018343,0.023139,-0.001202,...,0.003159,0.008814,-0.006446,-0.010817,-0.001418,0.000791,-0.007080,0.007446,-0.001812,7
2,0.000942,0.073674,-0.000899,-0.005003,-0.021424,0.008132,-0.002849,-0.019272,0.023842,-0.001526,...,-0.004015,-0.004902,-0.026883,0.002855,0.000616,-0.002268,0.030711,0.004014,0.006947,7
3,0.000718,0.056971,-0.001262,-0.005499,-0.016740,0.007987,-0.003522,-0.019913,0.025101,-0.005837,...,-0.041729,0.012890,-0.012335,-0.025678,-0.000179,0.009558,-0.008566,-0.011397,0.043441,7
4,0.000622,0.049215,-0.006535,-0.002369,-0.030595,0.013545,0.001310,-0.023610,0.035451,-0.001962,...,-0.005514,-0.003087,-0.001458,-0.003774,0.014519,0.014757,0.003819,0.005030,-0.000302,7

In [23]:
clf_not_deleted.head()

,3,0,1,2,3.1,4,5,6,7,8,...,40,41,42,43,44,45,46,47,48,49
0,7,0.919424,0.161102,-0.063145,-0.251941,0.061461,-0.429832,-1.374435,-0.082881,-0.040282,...,-0.596158,-0.164934,-0.758835,0.126125,0.903682,-0.321151,-0.069499,0.049566,0.841092,-0.636409
1,7,-0.418445,0.828959,0.128690,-0.144437,-0.744879,-0.054535,0.915078,0.568427,-0.003103,...,-0.422897,1.173202,-0.642290,-0.409585,0.371887,-1.080650,0.359601,-0.051756,1.054783,0.304581
2,7,0.337420,0.539516,0.533131,0.993997,0.261069,0.823869,-0.295720,0.077063,-0.029855,...,-0.878513,0.993566,-0.479820,-0.331973,-0.604365,-0.346948,-0.781054,-0.254095,1.279516,-1.160219
3,7,-0.329416,0.800199,-0.050267,0.120014,0.528244,0.083719,-0.257749,-0.228705,-0.415365,...,-0.021757,0.425311,-1.191278,-1.065843,0.732757,-0.421525,0.224690,0.557756,-0.228858,0.279815
4,7,-0.567168,0.504837,0.110849,-0.557441,0.261542,0.861513,-0.252615,1.071437,-0.439412,...,-0.031498,-0.120361,-1.131117,0.473464,0.313271,-0.614722,0.290234,-0.096546,0.354413,0.454233

In [24]:
X = clf_deleted.iloc[:,1:]
y = clf_deleted['3']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=22)

clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores.mean()

0.1693516178577597

In [25]:
X = clf_not_deleted.iloc[:,1:]
y = clf_not_deleted['3']

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=22)

clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores.mean()

0.1652524013700849

In [40]:
X = tfidf.iloc[:,:-1]
y = tfidf['3.1']

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state=22)

clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,random_state=0)
scores = cross_val_score(clf, X_train, y_train, cv=5)
scores.mean()

0.21151387119316176